name: Lint

on:
  push:
    branches:
      - main
      - develop
      - feature/**
  pull_request:

permissions:
  contents: read

jobs:
  lint:
    name: Super-Linter
    runs-on: ubuntu-latest

    permissions:
      contents: read
      statuses: write
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Super-Linter
        uses: super-linter/super-linter@v8.6.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

          # Analisa somente arquivos alterados no PR
          VALIDATE_ALL_CODEBASE: false

          # Linguagens utilizadas no projeto
          VALIDATE_JAVASCRIPT_ESTANDARD: true
          VALIDATE_JSON: true
          VALIDATE_MARKDOWN: true
          VALIDATE_YAML: true

          # Evita falhas por documentação e textos
          VALIDATE_NATURAL_LANGUAGE: true

          # Branch padrão
          DEFAULT_BRANCH: main